### ISSUE TITLE
Blank lines in dictionary aren't flagged by check-dictionary, cause crash

### ISSUE THREAD

**Issue by warmsocks** [codespell-project/codespell#1088]
Seen in codespell 1.15.0.dev0

If a blank line is introduced into the dictionary, `make check-dictionary` doesn't flag it as a problem, but when codespell is invoked, it crashes:

```
$ codespell
Traceback (most recent call last):
  File "/usr/bin/codespell", line 9, in <module>
    load_entry_point('codespell==1.15.0.dev0', 'console_scripts', 'codespell')()
  File "/usr/lib/python2.7/site-packages/codespell_lib/_codespell.py", line 579, in _script_main
    return main(*sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/codespell_lib/_codespell.py", line 625, in main
    build_dict(dictionary, misspellings, ignore_words)
  File "/usr/lib/python2.7/site-packages/codespell_lib/_codespell.py", line 316, in build_dict
    [key, data] = line.split('->')
ValueError: need more than 1 value to unpack
```
I would expect 

1. The check-dictionary target to flag blank lines as an error
2. A make target that would strip blank lines out, along with any leading or trailing whitespace.

I have a Makefile patch ready; I'll submit a PR.

**Comment by warmsocks** [comment]
#1089
