### ISSUE TITLE
Python3.7: Running the testsuite is failing with  TypeError: expected str, bytes or os.PathLike object, not LocalPath

### ISSUE THREAD

**Issue by sylvestre** [codespell-project/codespell#1249]
$ pytest-3 codespell_lib
```
Coverage.py warning: --include is ignored because --source is set (include-ignored)
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/main.py", line 180, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 629, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/hooks.py", line 306, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/cacheprovider.py", line 300, in pytest_configure
INTERNALERROR>     config.cache = Cache.for_config(config)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/cacheprovider.py", line 43, in for_config
INTERNALERROR>     cachedir = cls.cache_dir_from_config(config)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/cacheprovider.py", line 51, in cache_dir_from_config
INTERNALERROR>     return resolve_from_str(config.getini("cache_dir"), config.rootdir)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/pathlib.py", line 276, in resolve_from_str
INTERNALERROR>     root = Path(root)
INTERNALERROR>   File "/usr/lib/python3.7/pathlib.py", line 1003, in __new__
INTERNALERROR>     self = cls._from_parts(args, init=False)
INTERNALERROR>   File "/usr/lib/python3.7/pathlib.py", line 658, in _from_parts
INTERNALERROR>     drv, root, parts = self._parse_args(args)
INTERNALERROR>   File "/usr/lib/python3.7/pathlib.py", line 642, in _parse_args
INTERNALERROR>     a = os.fspath(a)
INTERNALERROR> TypeError: expected str, bytes or os.PathLike object, not LocalPath

```

**Comment by rednafi** [comment]
I'm also facing the same issue .....python 3.7.3 and pytest 5.3.2

**Comment by rednafi** [comment]
> you can also try `python -im pytest codespell_lib` then when it fails try to inspect it:
> 
> ```
> >>> import pdb; pdb.pm()
> (pdb) p a
> ```
> 
> to see what path it's complaining about. Or modify the `pytest` code locally so that it prints `a` on failure, etc.

```
>>> import pdb; pdb.pm()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/pdb.py", line 1629, in pm
    post_mortem(sys.last_traceback)
AttributeError: module 'sys' has no attribute 'last_traceback'```

**Comment by buhtz** [comment]
Can you reproduce the problem in the latest version? Is this still relevant today after 5 years?

**Comment by DimitriPapadopoulos** [comment]
Indeed. That must have been a pytest bug.
