### ISSUE TITLE
test problem with python 2.7

### ISSUE THREAD

**Issue by 0-wiz-0** [codespell-project/codespell#1865]
The self tests with python 2.7 report this error:
````
codespell_lib.tests.test_basic (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: codespell_lib.tests.test_basic (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: codespell_lib.tests.test_basic
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/pkg/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/scratch/devel/py-codespell/work/codespell-2.0.0/codespell_lib/tests/test_basic.py", line 29
    def main(self, *args, count=True, std=False, **kwargs):
                              ^
SyntaxError: invalid syntax
````

**Comment by larsoner** [comment]
We require 2.7+ nowadays

https://github.com/codespell-project/codespell#requirements

**Comment by larsoner** [comment]
Sorry I mean 3.5+...
