### ISSUE TITLE
codespell fails with uncaught exception on unreadable files

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2189]
```sh
$ mkdir -p foo/bar
$ touch foo/bar/file
$ chmod a= foo/bar/file
$ cd foo
$ 
$ codespell 
Traceback (most recent call last):
  File "/home/username/.local/bin/codespell", line 11, in <module>
    load_entry_point('codespell', 'console_scripts', 'codespell')()
  File "/my/path/codespell/codespell_lib/_codespell.py", line 746, in _script_main
    return main(*sys.argv[1:])
  File "/my/path/codespell/codespell_lib/_codespell.py", line 897, in main
    bad_count += parse_file(
  File "/my/path/codespell/codespell_lib/_codespell.py", line 630, in parse_file
    text = is_text_file(filename)
  File "/my/path/codespell/codespell_lib/_codespell.py", line 488, in is_text_file
    with open(filename, mode='rb') as f:
PermissionError: [Errno 13] Permission denied: './bar/file'
$ 
```

**Comment by peternewman** [comment]
Nice find, another warning to add like the missing files.

**Comment by DimitriPapadopoulos** [comment]
It could fail silently (as it does on files deleted after `os.walk()`) or emit a warning. In this case, I agree with you: we require a warning.
