### ISSUE TITLE
Weird egg-info file version in 2.2.2

### ISSUE THREAD

**Issue by hadess** [codespell-project/codespell#2533]
Using `python3-3.11.0~rc2-1.fc37.x86_64` and building codespell 2.2.2 results in an egg-info file called `codespell-0.1.dev1+g6faab65-py3.11.egg-info` instead of versioned according to the release.

The git sha shown is the one from the top of the git repository created by the Fedora packaging tool, to make it easier to apply git patches. Removing that git repo creation, I get:
```
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -sP'
Traceback (most recent call last):
  File "/home/hadess/Projects/Fedora/merged/codespell/rawhide/codespell-2.2.2/setup.py", line 6, in <module>
    setup()
  File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 139, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 477, in __init__
    _Distribution.__init__(
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 275, in __init__
    self.finalize_options()
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 901, in finalize_options
    ep(self)
  File "/usr/lib/python3.11/site-packages/setuptools_scm/integration.py", line 123, in infer_version
    _assign_version(dist, config)
  File "/usr/lib/python3.11/site-packages/setuptools_scm/integration.py", line 62, in _assign_version
    _version_missing(config)
  File "/usr/lib/python3.11/site-packages/setuptools_scm/__init__.py", line 109, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /home/hadess/Projects/Fedora/merged/codespell/rawhide/codespell-2.2.2.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by larsoner** [comment]
Do you have this problem when you use the .tar.gz source distribution from https://pypi.org/project/codespell/#files ? If not, then I suggest switching to using that and adding patches as you require

**Comment by larsoner** [comment]
There should now always be a 1-to-1 relationship between PyPi tarballs and GH releases (the GH release causes a PyPi release action to run). While yes it's possible in principle for us to add the infrastructure to do this in our action, it's a bit more to maintain and "stuff" that could break. So at your end if it's not (much) more than changing the URL to use the associated PyPi one, that seems like less total work overall.

But if somehow pointing to the PyPI URL and untarring it creates problems, then yes I can look into attaching the PyPI source `.tar.gz` to the GH release

**Comment by hadess** [comment]
The PyPi URL isn't nicely patterned though, it contains a whole bunch of hashes before the filename:
```
https://files.pythonhosted.org/packages/71/66/d5e8b69e1572e0165be57fd980ef74394dcea0f49d810407eab2c46449ef/codespell-2.2.1.tar.gz
https://files.pythonhosted.org/packages/42/57/2b07dc5eb131d34a820bbc08a4437ca2ddfff7a47476bffd1822437de910/codespell-2.2.2.tar.gz
```

I might need to figure out a way to do this more automatically...

**Comment by larsoner** [comment]
conda-forge packages almost always use this nice clean variant

https://github.com/conda-forge/codespell-feedstock/blob/4693db8d837d6e6f78790468a3c50c86e0299900/recipe/meta.yaml#L9

e.g., for codespell it would be 

https://pypi.io/packages/source/c/codespell/codespell-2.2.2.tar.gz

**Comment by larsoner** [comment]
Locally for me:
```
$ pip install https://pypi.io/packages/source/c/codespell/codespell-2.2.2.tar.gz
...
Successfully installed codespell-2.2.2
$ python -c "import codespell_lib; print(codespell_lib); print(codespell_lib.__version__)"
<module 'codespell_lib' from '/home/larsoner/.local/lib/python3.10/site-packages/codespell_lib/__init__.py'>
2.2.2
```
So unfortunately I cannot replicate.

The build system *does* need to support `pyproject.toml` building support, which requires fairly new `pip` and `setuptools`. Maybe these are too old?

**Comment by peternewman** [comment]
Isn't it because you're trying to do it for Python 3.11 which I don't think we support yet?

**Comment by hadess** [comment]
> Isn't it because you're trying to do it for Python 3.11 which I don't think we support yet?

Maybe, except that my local system uses `python3-3.11.0~rc2-1.fc37.x86_64`...

**Comment by hadess** [comment]
I removed the dynamic version from `pyproject.toml`, and it now generated an egg-info with the right version.

The difference between my local setup and the build system was that `python-setuptools_scm` wasn't installed on the build system, so python-setuptools silently failed to fetch the version.

Maybe `setup.py` should check for `python-setuptools_scm` so we don't run into this problem again? I can write a patch for that.

**Comment by larsoner** [comment]
Right now our setup.py is the two line wrapper recommended by the PyPI folks. Rather than deviate from that, we should ask them what the right thing to do is here. To me it suggests either their suggestion is incomplete, we are doing something else wrong, or their suggestion is wrong.

**Comment by hadess** [comment]
I honestly don't know enough about the fallout caused by the setuptools deprecation to be able to file a useful bug report. Would be happy to lurk and learn, so if you end up filing an issue, let me know.
