### ISSUE TITLE
latest release causes error in GitHub Action

### ISSUE THREAD

**Issue by bendichter** [codespell-project/codespell#2775]
```pytb
Traceback (most recent call last):
  File "/usr/local/bin/codespell", line 8, in <module>
    sys.exit(_script_main())
  File "/usr/local/lib/python3.8/site-packages/codespell_lib/_codespell.py", line 987, in _script_main
    return main(*sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/codespell_lib/_codespell.py", line 992, in main
    options, parser, used_cfg_files = parse_options(args)
  File "/usr/local/lib/python3.8/site-packages/codespell_lib/_codespell.py", line 568, in parse_options
    data = tomllib.load(f).get("tool", {})
UnboundLocalError: local variable 'tomllib' referenced before assignment
Codespell found one or more problems
```

**Comment by browniebroke** [comment]
Looks fixed in https://github.com/codespell-project/codespell/pull/2774
