### ISSUE TITLE
Codespell pre-commit hooks totally failing following the release of setuptools-scm==8.0.0

### ISSUE THREAD

**Issue by andrewmwilson** [codespell-project/codespell#3088]
Following the release of `setuptools-scm==8.0.0` around an hour ago, I believe all newly-installed codespell pre-commit hooks are failing with the following error.

```Traceback (most recent call last):
  File "/Users/a/.cache/pre-commit/repoczrniamn/py_env-python3.11/bin/codespell", line 5, in <module>
    from codespell_lib import _script_main
  File "/Users/a/.cache/pre-commit/repoczrniamn/py_env-python3.11/lib/python3.11/site-packages/codespell_lib/__init__.py", line 1, in <module>
    from ._codespell import _script_main, main
  File "/Users/a/.cache/pre-commit/repoczrniamn/py_env-python3.11/lib/python3.11/site-packages/codespell_lib/_codespell.py", line 29, in <module>
    from ._version import __version__ as VERSION  # noqa: N812
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a/.cache/pre-commit/repoczrniamn/py_env-python3.11/lib/python3.11/site-packages/codespell_lib/_version.py", line 4
    __version__ : str = version : str = '0.1.dev1+g355e50e'
                                ^
SyntaxError: invalid syntax

**Comment by andrewmwilson** [comment]
Looks like this is an issue with setuptools-scm, so codespell might not have to do much other than wait for a fix.

https://github.com/pypa/setuptools_scm/issues/905
https://github.com/pypa/setuptools_scm/issues/906

**Comment by andrewmwilson** [comment]
Looks like this has been resolved upstream.

**Comment by tomrijntjes** [comment]
Not so. Opened a PR to fix the immediate issue: https://github.com/codespell-project/codespell/pull/3100
