### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#322]
Recreate bug:  
+ Use latest HEAD of codespell
+ `git clone https://github.com/nextcloud/server nextcloud-server`
+ `cd nextcloud-server/`
+ run `codespell -q 3`

codespell finds typos, aka a short list is generated then suddenly a crash. 

Crash: 
```
 Traceback (most recent call last):
  File "/home/beast/.local/bin/codespell", line 11, in <module>
    load_entry_point('codespell==1.12.0.dev0', 'console_scripts', 'codespell')()
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 557, in _script_main
    return main(*sys.argv[1:])
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 636, in main
    bad_count += parse_file(fname, colors, summary)
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 532, in parse_file
    'RIGHTWORD': crightword, 'REASON': creason})
UnicodeEncodeError: 'ascii' codec can't encode character '\xed' in position 88: ordinal not in range(128)
```

**Comment by larsoner** [comment]
Can you make a minimal example by isolating the offending line in the file that failed?

**Comment by luzpaz** [comment]
Weird I can't recreate it again...

**Comment by luzpaz** [comment]
Crash again different repo. Can't recreate it consistently. Putting error here for further examination:
```
Traceback (most recent call last):
  File "/home/beast/.local/bin/codespell", line 11, in <module>
    load_entry_point('codespell==1.12.0.dev0', 'console_scripts', 'codespell')()
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 557, in _script_main
    return main(*sys.argv[1:])
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 636, in main
    bad_count += parse_file(fname, colors, summary)
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 485, in parse_file
    options.interactive)
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 364, in ask_for_word_fix
    print("%s\t%s  ==> %s (Y/n) " % (line, wrongword, fixword), end='')
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 63: ordinal not in range(128)
```

**Comment by peternewman** [comment]
It looks like this is probably the same as:
https://github.com/codespell-project/codespell/issues/416

It would help to know a specific commit it fails on in either repo, the reason you can't recreate it is possibly because they fixed the underlying typo.

**Comment by luzpaz** [comment]
+ `git clone https://github.com/QGIS/QGIS`
+ `cd QGIS/`
+ `codespell -q 3`

```
Traceback (most recent call last):
  File "/home/beast/.local/bin/codespell", line 11, in <module>
    load_entry_point('codespell==1.14.0.dev0', 'console_scripts', 'codespell')()
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 560, in _script_main
    return main(*sys.argv[1:])
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 645, in main
    bad_count += parse_file(filename, colors, summary)
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 535, in parse_file
    'RIGHTWORD': crightword, 'REASON': creason})
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 70: ordinal not in range(128)
```

**Comment by luzpaz** [comment]
@peternewman sorry, i don't know since I rebased several times since AND I can't recreate the crash. bummer. I'll note the commit next time.

**Comment by larsoner** [comment]
Okay feel free too reopen or make a new issue if it happens again
