### ISSUE TITLE
Testsuite is failing on TypeError: test_case_handling() missing 1 required positional argument: 'reload_codespell_lib'

### ISSUE THREAD

**Issue by sylvestre** [codespell-project/codespell#531]
Using a Debian testing

```
nosetests3 -e "test_command"
...EE.....E
======================================================================
ERROR: Test ignore dictionary functionality
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_ignore_dictionary() missing 1 required positional argument: 'reload_codespell_lib'

======================================================================
ERROR: Test custom word regex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_custom_regex() missing 1 required positional argument: 'reload_codespell_lib'

======================================================================
ERROR: Test that capitalized entries get detected properly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_case_handling() missing 1 required positional argument: 'reload_codespell_lib'

----------------------------------------------------------------------
Ran 11 tests in 3.081s

FAILED (errors=3)

```

**Comment by larsoner** [comment]
`codespell` uses `pytest`. `nosetests` is no longer maintained.
