### ISSUE TITLE
crash running codespell --help 

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#604]
running most up to date 1.14.0.dev0

```
[foo@bar]$ codespell --help
Traceback (most recent call last):
  File "/home/beast/.local/bin/codespell", line 11, in <module>
    load_entry_point('codespell==1.14.0.dev0', 'console_scripts', 'codespell')()
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 565, in _script_main
    return main(*sys.argv[1:])
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 574, in main
    options, args, parser = parse_options(args)
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 288, in parse_options
    (o, args) = parser.parse_args(list(args))
  File "/usr/lib/python3.6/optparse.py", line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib/python3.6/optparse.py", line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib/python3.6/optparse.py", line 1501, in _process_long_opt
    option.process(opt, value, values, self)
  File "/usr/lib/python3.6/optparse.py", line 785, in process
    self.action, self.dest, opt, value, values, parser)
  File "/usr/lib/python3.6/optparse.py", line 807, in take_action
    parser.print_help()
  File "/usr/lib/python3.6/optparse.py", line 1647, in print_help
    file.write(self.format_help())
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 1349: ordinal not in range(128)
```

**Comment by larsoner** [comment]
I can't replicate locally. Travis (Linux and macOS) and AppVeyor (Windows) run `codespell --help` and have not shown any errors, either.

**Comment by larsoner** [comment]
... so I'm not sure how to replicate. Can you try uninstalling and reinstalling `codespell` perhaps? Or maybe the version you installed had some modified character?

**Comment by luzpaz** [comment]
I uninstalled and reinstalled. Same error. No joy.
```
[beast@beast ]$ pip3 uninstall codespell
Uninstalling codespell-1.14.0.dev0:
  Would remove:
    /home/beast/.local/bin/codespell
    /home/beast/.local/lib/python3.6/site-packages/codespell-1.14.0.dev0-py3.6.egg-info
    /home/beast/.local/lib/python3.6/site-packages/codespell_lib/*
Proceed (y/n)? y
  Successfully uninstalled codespell-1.14.0.dev0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[beast@beast ]$ pip3 install --user --upgrade git+https://github.com/codespell-project/codespell.git
Collecting git+https://github.com/codespell-project/codespell.git
  Cloning https://github.com/codespell-project/codespell.git to /tmp/pip-req-build-hwyem8n9
Installing collected packages: codespell
  Running setup.py install for codespell ... done
Successfully installed codespell-1.14.0.dev0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[beast@beast ]$ codespell --help
Traceback (most recent call last):
  File "/home/beast/.local/bin/codespell", line 11, in <module>
    load_entry_point('codespell==1.14.0.dev0', 'console_scripts', 'codespell')()
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 565, in _script_main
    return main(*sys.argv[1:])
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 574, in main
    options, args, parser = parse_options(args)
  File "/home/beast/.local/lib/python3.6/site-packages/codespell_lib/_codespell.py", line 288, in parse_options
    (o, args) = parser.parse_args(list(args))
  File "/usr/lib/python3.6/optparse.py", line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib/python3.6/optparse.py", line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib/python3.6/optparse.py", line 1501, in _process_long_opt
    option.process(opt, value, values, self)
  File "/usr/lib/python3.6/optparse.py", line 785, in process
    self.action, self.dest, opt, value, values, parser)
  File "/usr/lib/python3.6/optparse.py", line 807, in take_action
    parser.print_help()
  File "/usr/lib/python3.6/optparse.py", line 1647, in print_help
    file.write(self.format_help())
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 1349: ordinal not in range(128)
```

**Comment by peternewman** [comment]
This smacks of Microsoft "Smart" Quotes or similar having snuck in somewhere, rendering the curly ones rather than the normal symmetric ones.

**Comment by peternewman** [comment]
Indeed there's one in the regex that's part of the help:
https://github.com/codespell-project/codespell/pull/418

Try editing out line 41's word_regex second apostrophe @luzpaz and see if that at least fixes it.
